spring:
  application:
    name: xalispain-backend

  profiles:
    active: dev

  datasource:
    hikari:
      pool-name: XalisPain-HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000      # 5 minutes
      connection-timeout: 20000 # 20 secondes
      max-lifetime: 1200000     # 20 minutes
      auto-commit: true

server:
  servlet:
    context-path: /xalispain/api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env,threaddump,heapdump
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      environment: dev
      version: 0.0.1-SNAPSHOT
    distribution:
      sla:
        http.server.requests: 10ms,100ms,1s
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true